- name: setting up app directory
  ansible.builtin.import_role:
    name: common
    tasks_from: app-set-up


- name: setting nodejs
  ansible.builtin.import_role:
    name: common
    tasks_from: nodejs

- name: setting up mongodb
  ansible.builtin.import_role:
    name: common
    tasks_from: mongodb-setup

- name: restarting and enabling service
  ansible.builtin.import_role:
    name: common
    tasks_from: systemd
