- name: "Adding user roboshop"
  ansible.builtin.user:
    name: roboshop

- name: 'Checking app directory is present or not'
  ansible.builtin.file:
    path: /app
    state: absent

- name: 'Creating app directory'
  ansible.builtin.file:
    path: /app
    state: directory

- name: 'Down loading code '
  ansible.builtin.get_url:
    url: "https://roboshop-builds.s3.amazonaws.com/{{ component }}.zip"
    dest: /tmp

- name: Unzipping the code'
  ansible.builtin.unarchive:
    src: "/tmp/{{ component }}.zip"
    dest: /app
    remote_src: yes

