- name: "copying {{ component }} service file"
  ansible.builtin.copy:
    src: "{{ component }}.service"
    dest: "/etc/systemd/system/{{ component }}.service"

- name: Reloading baemon 
  ansible.builtin.systemd_service:
    daemon_reload: yes

- name: "Enabling and restarting {{ component }}"
  ansible.builtin.service:
    name: "{{ component }}""
    state: restarted
    enabled: yes